name: Intro to ci

on:
  push:


jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false


      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build